sudo: required
language: php
php:
    - '7.0'
    - '7.1'

before_script:
  - composer install -o

after_script:
    - |
      if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
        travis_retry wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
      fi

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - wget -N https://getcomposer.org/composer.phar

script: ./vendor/bin/phpunit --configuration=phpunit.xml